package io.github.clamentos.cachecruncher.error.exceptions;

///
public final class EntityAlreadyExistsException extends CacheCruncherException {

    ///
    public EntityAlreadyExistsException(Throwable cause) {

        super(cause);
    }

    ///
}
